name: Build

permissions:
  contents: read

on:
  push:

jobs:

  macos:
    runs-on: macos-15
    permissions:
      contents: write
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Set up workspace
        run: |
          brew install itstool cargo-c gobject-introspection
          brew unlink cairo xz lz4
          python -m venv .venv
          .venv/bin/pip install meson ninja gi-docgen docutils
      - name: Installed homebrew packages
        run: brew list
      - name: Phase one - build GLib
        run: |
          source .venv/bin/activate
          meson setup --prefix=$(pwd)/_install _build
          meson install -C _build
      - name: Phase two - build cairo, pango
        run: |
          source .venv/bin/activate
          meson setup --prefix=$(pwd)/_install --reconfigure -Dphase=two _build
          meson install -C _build
      - name: Phase two - build libadwaita
        run: |
          source .venv/bin/activate
          meson setup --prefix=$(pwd)/_install --reconfigure -Dphase=three _build
          meson install -C _build
      - name: Phase three - rebuild librsvg
        run: |
          ./librsvg-pixbuf-loader.sh $(pwd)/_install
      - name: Phase four - make libraries relocatable
        run: |
          bin/fix-shared-libraries "$(pwd)/_install"
          cp bin/post-install "$(pwd)/_install"
      - name: Upload Adwaita-Framework
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: Adwaita-Framework
          path: _install/
